steps:
  # hello world
  - name: ubuntu:20.04
    id: 'hello world'
    args:
      - echo
      - hello world

  # Show docker credentials
  - name: ubuntu:20.04
    args:
      - echo
      - "org: ${_DOCKERHUB_ORGANISATION},    repo: ${_DOCKERHUB_REPOSITORY}"

  # Show default substitutions, execute multi-line commands
  - name: ubuntu:20.04
    entrypoint: bash
    args:
      - '-c'
      - |
        echo    "ID of Cloud project:     ${PROJECT_ID}" \
        && echo "ID of build:             ${BUILD_ID}" \
        && echo "project number:          ${PROJECT_NUMBER}" \
        && echo "trigger name:            ${TRIGGER_NAME}" \
        && echo "commit ID:               ${COMMIT_SHA}" \
        && echo "short SHA:               ${SHORT_SHA}" \
        && echo "name of repository:      ${REPO_NAME}" \
        && echo "name of branch:          ${BRANCH_NAME}" \
        && echo "name of tag:             ${TAG_NAME}" \
        && echo "build config file:       ${TRIGGER_BUILD_CONFIG_PATH}" \
        && echo "head branch of PR:       ${_HEAD_BRANCH}" \
        && echo "base branch of PR:       ${_BASE_BRANCH}" \
        && echo "url of head repo of PR:  ${_HEAD_REPO_URL}" \
        && echo "PR number:               ${_PR_NUMBER}"

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$_DOCKERHUB_USERNAME --password=$$DOCKERHUB_TOKEN']
    secretEnv: ['DOCKERHUB_TOKEN']

  # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_DOCKERHUB_ORGANISATION/$_DOCKERHUB_REPOSITORY:$SHORT_SHA', '.']

  # Docker ps
  - name: 'gcr.io/cloud-builders/docker'
    args: ['images']

substitutions:
  _DOCKERHUB_ORGANISATION: "aliarsal"
  _DOCKERHUB_USERNAME: "aliarsal"
  _DOCKERHUB_REPOSITORY: "workshop-project-backend"

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DOCKERHUB_TOKEN/versions/1
    env: 'DOCKERHUB_TOKEN'
